#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

users:
  - name: ${droplet_uname}
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys:
      - ${public_key}

packages:
  - unattended-upgrades
