
version: "3.7"
services:
  backend:
    image: nginx
    deploy:
      mode: global
    volumes:
      - nginx_content:/usr/share/nginx/html

    ports:
      - 8080:80
  app:
    image: html_builder:test
    deploy:
      mode: global
    volumes:
      - nginx_content:/data
volumes:
    nginx_content: