version: "3.7"
services:
  backend:
    image: uigctaw/metadata-social:nginx-test
    volumes:
      - myapp:/usr/share/nginx/html
    ports:
     - 8080:80
  app:
    image: uigctaw/metadata-social:pyapp
    volumes:
      - myapp:/app
volumes:
    myapp:

