version: "3.7"
services:
  backend:
    image: uigctaw/metadata-social-nginx:test
    deploy:
      mode: global
    volumes:
      - myapp:/usr/share/nginx/html
      - type: bind
        source: /srv/certs/live
        target: /srv/certs/live

    ports:
      - 443:443
  app:
    image: uigctaw/metadata-social-pyapp:test
    deploy:
      mode: global
    volumes:
      - myapp:/app
volumes:
    myapp:

